function data() {
  return [
    {
      name: "Bitcoin",
      code: "BTC",
      logo: "btc.png",
      buy_price: 4324.75,
      sell_price: 4668.93,
      change: 2280.66,
      change_percentage: 5.19,
      color: "#FFEFD8",
    },
    {
      name: "Ethereum",
      code: "ETH",
      logo: "eth.png",
      buy_price: 312.2938,
      sell_price: 321.9382,
      change: 194.234,
      change_percentage: 6.19,
      color: "#EFEFEF",
    },
    {
      name: "Apple",
      code: "AAPL",
      logo: "aapl.svg",
      buy_price: 4324.75,
      sell_price: 4668.93,
      change: -8.41,
      change_percentage: -0.49,
      color: "#F0F0F0",
    },
    {
      name: "Alphabet",
      code: "GOOG",
      logo: "goog.png",
      buy_price: 4324.75,
      sell_price: 4668.93,
      change: 5480.66,
      change_percentage: 5.19,
      color: "#DCEFFF",
    },
    {
      name: "Amazon",
      code: "AMZN",
      logo: "amzn.png",
      buy_price: 312.2938,
      sell_price: 321.9382,
      change: 124.234,
      change_percentage: 6.19,
      color: "#EFEFEF",
    },
    {
      name: "Commerzb",
      code: "CBK.DE",
      logo: "cbk.de.jpeg",
      buy_price: 4324.75,
      sell_price: 4668.93,
      change: -5.6,
      change_percentage: -0.49,
      color: "#F3DBB6",
    },
  ];
}

export default data;
